"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](lavender)\
$username\
[](bg:red fg:lavender)\
$directory\
[](fg:red bg:pink)\
$git_branch\
$git_status\
[](fg:pink bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:surface0)\
$docker_context\
[](fg:surface0 bg:teal)\
$time\
[ ](fg:teal)\
$line_break$character"""

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[username]
show_always = true
format = '[ $user ](bg:lavender fg:mantle)'

[directory]
format = "[ $path ](bg:red fg:mantle)"
truncation_length = 3
truncation_symbol = "…/"


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Code" = "󰅱 "
"Classes" = "󰑴 "

[git_branch]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:mantle bg:pink)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:mantle bg:pink)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $context) ](fg:#83a598 bg:surface0)]($style)'

[time]
disabled = false
time_format = "%I:%M:%S %p"
style = "bg:base"
format = '[[  $time ](fg:mantle bg:teal)]($style)'

[line_break]
disabled = false

[character]
disabled = false
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
